const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"


export {USER_LOGIN_FAILURE,USER_LOGIN_REQUEST,USER_LOGIN_SUCCESS}